export class TenantNewDetailedV2Params {
  public sCorpCode: string;
  public sLocationCode: string;
  public sCorpUserName: string;
  public sCorpPassword: string;
  public sWebPassword: string;
  public sMrMrs: string;
  public sFName: string;
  public sMI: string;
  public sLName: string;
  public sCompany: string;
  public sAddr1: string;
  public sAddr2: string;
  public sCity: string;
  public sRegion: string;
  public sPostalCode: string;
  public sCountry: string;
  public sPhone: string;
  public sMrMrsAlt: string;
  public sFNameAlt: string;
  public sMIAlt: string;
  public sLNameAlt: string;
  public sAddr1Alt: string;
  public sAddr2Alt: string;
  public sCityAlt: string;
  public sRegionAlt: string;
  public sPostalCodeAlt: string;
  public sCountryAlt: string;
  public sPhoneAlt: string;
  public sMrMrsBus: string;
  public sFNameBus: string;
  public sMIBus: string;
  public sLNameBus: string;
  public sCompanyBus: string;
  public sAddr1Bus: string;
  public sAddr2Bus: string;
  public sCityBus: string;
  public sRegionBus: string;
  public sPostalCodeBus: string;
  public sCountryBus: string;
  public sPhoneBus: string;
  public sFax: string;
  public sEmail: string;
  public sPager: string;
  public sMobile: string;
  public bCommercial: boolean;
  public bCompanyIsTenant: boolean;
  public dDOB: string;
  public sTenNote: string;
  public sLicense: string;
  public sLicRegion: string;
  public sSSN: string;
  public sGateCode: string;

  constructor(data: any) {
    this.sCorpCode = data.sCorpCode ?? "";
    this.sLocationCode = data.sLocationCode ?? "";
    this.sCorpUserName = data.sCorpUserName ?? "";
    this.sCorpPassword = data.sCorpPassword ?? "";
    this.sWebPassword = data.sWebPassword ?? "";
    this.sMrMrs = data.sMrMrs ?? "";
    this.sFName = data.sFName ?? "";
    this.sMI = data.sMI ?? "";
    this.sLName = data.sLName ?? "";
    this.sCompany = data.sCompany ?? "";
    this.sAddr1 = data.sAddr1 ?? "";
    this.sAddr2 = data.sAddr2 ?? "";
    this.sCity = data.sCity ?? "";
    this.sRegion = data.sRegion ?? "";
    this.sPostalCode = data.sPostalCode ?? "";
    this.sCountry = data.sCountry ?? "";
    this.sPhone = data.sPhone ?? "";
    this.sMrMrsAlt = data.sMrMrsAlt ?? "";
    this.sFNameAlt = data.sFNameAlt ?? "";
    this.sMIAlt = data.sMIAlt ?? "";
    this.sLNameAlt = data.sLNameAlt ?? "";
    this.sAddr1Alt = data.sAddr1Alt ?? "";
    this.sAddr2Alt = data.sAddr2Alt ?? "";
    this.sCityAlt = data.sCityAlt ?? "";
    this.sRegionAlt = data.sRegionAlt ?? "";
    this.sPostalCodeAlt = data.sPostalCodeAlt ?? "";
    this.sCountryAlt = data.sCountryAlt ?? "";
    this.sPhoneAlt = data.sPhoneAlt ?? "";
    this.sMrMrsBus = data.sMrMrsBus ?? "";
    this.sFNameBus = data.sFNameBus ?? "";
    this.sMIBus = data.sMIBus ?? "";
    this.sLNameBus = data.sLNameBus ?? "";
    this.sCompanyBus = data.sCompanyBus ?? "";
    this.sAddr1Bus = data.sAddr1Bus ?? "";
    this.sAddr2Bus = data.sAddr2Bus ?? "";
    this.sCityBus = data.sCityBus ?? "";
    this.sRegionBus = data.sRegionBus ?? "";
    this.sPostalCodeBus = data.sPostalCodeBus ?? "";
    this.sCountryBus = data.sCountryBus ?? "";
    this.sPhoneBus = data.sPhoneBus ?? "";
    this.sFax = data.sFax ?? "";
    this.sEmail = data.sEmail ?? "";
    this.sPager = data.sPager ?? "";
    this.sMobile = data.sMobile ?? "";
    this.bCommercial = false;
    this.bCompanyIsTenant = false;
    this.dDOB = new Date(1970, 0, 1).toISOString();
    this.sTenNote = data.sTenNote ?? "";
    this.sLicense = data.sLicense ?? "";
    this.sLicRegion = data.sLicRegion ?? "";
    this.sSSN = data.sSSN ?? "";
    this.sGateCode = data.sGateCode ?? "1516";
  }
}